{
 "title": "IoT FleetWise demo",
 "panels": [
  {
   "title": "Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "targets": [
    {
     "database": "\"fleetwisedb\"",
     "measure": "OBD.Speed",
     "rawQuery": "SELECT * FROM \"fleetwisedb\".\"campaign\" WHERE measure_name='OBD.Speed'",
     "table": "\"campaign\""
    }
   ]
  },
  {
   "title": "Engine Speed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "database": "\"fleetwisedb\"",
     "measure": "OBD.CoolantTemperature",
     "rawQuery": "SELECT * FROM \"fleetwisedb\".\"campaign\" WHERE measure_name='OBD.EngineSpeed'",
     "table": "\"campaign\""
    }
   ]
  },
  {
   "title": "Coolant Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "database": "\"fleetwisedb\"",
     "measure": "OBD.CoolantTemperature",
     "rawQuery": "SELECT * FROM \"fleetwisedb\".\"campaign\" WHERE measure_name='OBD.CoolantTemperature'",
     "table": "\"campaign\""
    }
   ]
  }
 ]
}